# Generated by Django 3.2.5 on 2021-07-29 17:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('is_expired', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(null=True, related_name='category', to='todo.Category'),
        ),
    ]
