# Generated by Django 3.2.5 on 2021-07-30 07:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210730_1204'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
