# Generated by Django 3.2.5 on 2021-07-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210730_1229'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
    ]
