# Generated by Django 3.2.5 on 2021-07-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'unimportant'), (1, 'important'), (3, 'urgent')], default=4),
        ),
    ]
