# Generated by Django 3.2.5 on 2021-07-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_task__status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='_status',
            field=models.CharField(choices=[('E', 'Expired'), ('C', 'Continuous')], db_column='status', max_length=1, verbose_name='status'),
        ),
    ]
