# Generated by Django 3.2.5 on 2021-07-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_task__status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='_status',
        ),
    ]
